## config.yaml
dataset:
  name: Apnea-ECG
  source_url: https://physionet.org/content/apnea-ecg/1.0.0/
  sampling_rate: 100
  segment_lengths:
    - 180
  preprocessing:
    bandpass_filter:
      lowcut: 0.5
      highcut: 48
      order: 4
    normalization: z-score

model:
  cnn:
    # num_layers is now hardcoded in model.py as per paper's fixed architecture
    # kernel_size is also hardcoded
    dropout: 0.3
    activation: relu
  transformer:
    encoder_decoder: false # This is consistent
    dropout: 0.3
    # model_dim: 64
    # num_encoder_layers: 2
    # nhead: 2
    # dim_feedforward: 128

training:
  optimizer: adam
  learning_rate: 0.001
  betas:
    beta1: 0.9
    beta2: 0.999
  epsilon: 1e-8
  batch_size: 32
  epochs: 70
  loss_function: cross_entropy # Loss is standard cross-entropy, not weighted

evaluation:
  metrics:
    - accuracy
    - sensitivity
    - specificity
    - f1_score
    - auc
  segment_wise:
    window_sizes:
      - 180
  recording_wise:
    classification_accuracy: true
    ahi_mae: true