## config.yaml
dataset:
  name: Apnea-ECG
  source_url: https://physionet.org/content/apnea-ecg/1.0.0/
  sampling_rate: 100
  segment_lengths:
    - 60   # in seconds, 1-minute segments
    - 180  # in seconds, 3-minute segments
  preprocessing:
    bandpass_filter:
      lowcut: 0.5
      highcut: 48
      order: 4
    normalization: z-score  # assumed per segment normalization

model:
  cnn:
    num_layers: 10
    dropout: 0.3
    activation: relu
  transformer:
    encoder_decoder: true
    dropout: 0.3
    # Specific transformer parameters are not provided in the paper and should be configurable

training:
  optimizer: adam
  learning_rate: 0.001
  betas:
    beta1: 0.9
    beta2: 0.999
  epsilon: 1e-8
  batch_size: 32
  epochs: 70
  loss_function: cross_entropy

evaluation:
  metrics:
    - accuracy
    - sensitivity
    - specificity
    - f1_score
    - auc
  segment_wise:
    window_sizes:
      - 60
      - 180
  recording_wise:
    classification_accuracy: true
    ahi_mae: true