dataset:
  name: Apnea-ECG
  source_url: https://physionet.org/content/apnea-ecg/1.0.0/
  root_dir: apnea-ecg  # اضافه کردن این خط
  sampling_rate: 100
  segment_lengths: [60]
  
preprocessing:  # این بخش باید دقیقاً با این نام وجود داشته باشد
  bandpass_filter:
    lowcut: 0.5
    highcut: 48
    order: 4
  normalization: z-score

model:
  cnn:
    num_layers: 6
    dropout: 0.3
    activation: relu
  transformer:
    encoder_decoder: false
    dropout: 0.3
    num_encoder_layers: 2
    nhead: 4
    dim_feedforward: 256
    model_dim: 64

training:
  optimizer: adamw
  learning_rate: 0.0005
  weight_decay: 0.001
  batch_size: 32
  epochs: 50
  loss_function: weighted_cross_entropy

evaluation:
  metrics:
    - accuracy
    - sensitivity
    - specificity
    - f1_score
    - auc