## config.yaml
dataset:
  name: Apnea-ECG
  source_url: https://physionet.org/content/apnea-ecg/1.0.0/
  sampling_rate: 100
  segment_lengths:
    - 60
  preprocessing:
    bandpass_filter:
      lowcut: 0.5
      highcut: 48
      order: 4
    normalization: z-score

model:
  cnn:
    num_layers: 10
    # <--- FIX: Increased dropout to reduce overfitting --->
    dropout: 0.5
    activation: relu
  transformer:
    encoder_decoder: false
    # <--- FIX: Increased dropout to reduce overfitting --->
    dropout: 0.5

training:
  optimizer: adam
  learning_rate: 0.0001 # <--- FIX: Lowered learning rate for more stable training
  # <--- FIX: Added new parameters for the trainer --->
  weight_decay: 0.0001
  early_stopping_patience: 10
  # --- Removed obsolete parameters like betas and epsilon for simplicity ---
  batch_size: 32
  epochs: 70
  loss_function: cross_entropy

evaluation:
  metrics:
    - accuracy
    - sensitivity
    - specificity
    - f1_score
    - auc
  segment_wise:
    window_sizes:
      - 60
      - 180
  recording_wise:
    classification_accuracy: true
    ahi_mae: true