## config.yaml
dataset:
  name: Apnea-ECG
  source_url: https://physionet.org/content/apnea-ecg/1.0.0/
  sampling_rate: 100
  segment_lengths:
    - 60
  preprocessing:
    bandpass_filter:
      lowcut: 0.5
      highcut: 48
      order: 4
    normalization: z-score

model:
  cnn:
    num_layers: 10
    # <--- FIX: Lowered dropout slightly to give the model more learning capacity
    dropout: 0.4
    activation: relu
  transformer:
    encoder_decoder: false
    # <--- FIX: Lowered dropout slightly
    dropout: 0.4

training:
  optimizer: adam
  # <--- FIX: Slightly increased learning rate to give the model more momentum
  learning_rate: 0.0005 
  weight_decay: 0.0001
  early_stopping_patience: 10
  batch_size: 32
  epochs: 70
  loss_function: cross_entropy # This is just a name, the code now uses weighted loss

evaluation:
  metrics:
    - accuracy
    - sensitivity
    - specificity
    - f1_score
    - auc
  segment_wise:
    window_sizes:
      - 60
      - 180
  recording_wise:
    classification_accuracy: true
    ahi_mae: true